# The name of the job is what will display on the GitHub repository in the Actions tab.
name: First Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened]
# This section covers the work to perform.
# We include one or more jobs in this section.
jobs: 
  job1:   
    runs-on: ubuntu-latest

    # Each job contains one or more steps. A step needs to have at least a name and a command.
    steps:
    - name: Step one      
      run: echo "Step 1 complete!"
      # This section does not appear in the solution file but demonstrates how to set
      # custom variables that will be available in the run script.      
    - name: Step two
      run: echo "Step 2 complete!"
      
  job2:
    # Job 2 will only run after job 1 completes.
    # Removing this 'needs' section would make the jobs run simultaneously.
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Cowsays
      # The 'uses' command executes a remote GitHub action.
      # A command like mscoutermarsh/cowsays-action means you can
      # find this code at https://github.com/mscoutermarsh/cowsays-action
      uses: mscoutermarsh/cowsays-action@master
      # The 'with' block includes parameters that the workflow will pass
      # to this action. Parameters are all in key-value format.
      with:
        text: 'Ready for prod--ship it!'
        color: 'magenta'
